record:
  - "^/tf$"
  - "^/diagnostics$"
  - "^/system/processing_time_checker/metrics$"
  - "^/sensing/lidar/concatenated/pointcloud$"
  - "^/perception/object_recognition/detection/objects$"
  - "^/perception/object_recognition/tracking/objects$"
  - "^/perception/object_recognition/objects$"
  - "^/perception/object_recognition/tracking/multi_object_tracker/debug/.*"
  - "^/perception/object_recognition/detection/.*/debug/pipeline_latency_ms$"
  - "^/perception/perception_online_evaluator/.*"
  - "^/driving_log_replayer/.*"
