record:
  - "^/tf$"
  - "^/diagnostics$"
  - "^/system/processing_time_checker/metrics$"
  - "^/map/vector_map_marker$"
  - "^/map/pointcloud_map$"
  - "^/localization/pose_estimator/exe_time_ms$"
  - "^/localization/pose_estimator/iteration_num$"
  - "^/localization/pose_estimator/transform_probability$"
  - "^/localization/pose_estimator/nearest_voxel_transformation_likelihood$"
  - "^/localization/pose_estimator/initial_to_result_relative_pose$"
  - "^/localization/pose_estimator/ndt_marker$"
  - "^/localization/pose_estimator/pose$"
  - "^/localization/pose_estimator/pose_with_covariance$"
  - "^/localization/kinematic_state$"
  - "^/localization/acceleration$"
  - "^/localization/reference_kinematic_state$"
  - "^/localization/util/downsample/pointcloud$"
  - "^/localization/pose_estimator/points_aligned$"
  - "^/system/processing_time_checker/metrics$"
  - "^/driving_log_replayer/.*$"
  - "^/sensing/gnss/septentrio/nav_sat_fix"
