record:
  - "^/tf$"
  - "^/perception/obstacle_segmentation/pointcloud$"
  - "^/diagnostics$"
  - "^/system/processing_time_checker/metrics$"
  - "^/sensing/lidar/.*/blockage_diag/debug/blockage_mask_image$"
  - "^/sensing/lidar/.*/pointcloud_raw_ex$"
  - "^/driving_log_replayer_v2/.*"
  - "^/driving_log_replayer/.*"
