# planning_control profile for x2 j6_gen2 with raw CAN replay for j6_can_interface
publish:
  # CAN (required to regenerate /j6/can/status/m0_status, m1_status, m2_status, m3_status)
  - /j6/fintekcan0/from_can_bus
  - /j6/peakcan0/from_can_bus
  - /j6/peakcan1/from_can_bus
  # vehicle
  - /vehicle/status/steering_status
  - /vehicle/status/velocity_status
  - /vehicle/status/turn_indicators_status
  - /vehicle/status/control_mode
  - /vehicle/status/gear_status
  # sensing
  - /sensing/imu/imu_data
  # localization
  - /localization/acceleration
  - /localization/kinematic_state
  - /tf
  # perception
  - /perception/obstacle_segmentation/pointcloud
  - /perception/traffic_light_recognition/traffic_signals
  - /perception/occupancy_grid_map/map
  - /perception/object_recognition/objects
  # planning inputs
  - /planning/mission_planning/route
  - /planning/mission_planning/state
  - /planning/scenario_planning/max_velocity_default
  # system / mrm
  - /system/hazard_lights_cmd
  - /system/emergency/control_cmd
  - /system/emergency/gear_cmd
  - /system/emergency/hazard_lights_cmd
  - /system/emergency/turn_indicators_cmd
  - /system/fail_safe/mrm_state
  # /control/command
  - /control/command/control_cmd
  # `/control/external_cmd_selector` outputs
  - /control/external_cmd_selector/current_selector_mode
  - /external/selected/gear_cmd
  - /external/selected/hazard_lights_cmd
  - /external/selected/heartbeat
  - /external/selected/pedals_cmd
  - /external/selected/steering_cmd
  - /external/selected/turn_indicators_cmd
  # other
  - /autoware/state
  - /awapi/tmp/virtual_traffic_light_states
  - /api/operation_mode/state
  - /sensing/gnss/septentrio/nav_sat_fix
  - /planning/ground_truth_trajectory
  - /planning/trajectory

remap:
  - /planning/trajectory # it will be remapped to /planning/reference_trajectory
  - /control/command/control_cmd # it will be remapped to /control/reference_control_cmd
