/diagnostics:
  reliability: best_effort
  history: keep_last
  depth: 100
  durability: volatile
/tf_static:
  reliability: reliable
  history: keep_last
  depth: 1
  durability: transient_local
/perception/obstacle_segmentation/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/perception/obstacle_segmentation/single_frame/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/localization/util/downsample/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/sensing/lidar/concatenated/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/planning/mission_planning/route:
  reliability: reliable
  history: keep_last
  depth: 1
  durability: transient_local
/sensing/camera/camera0/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera1/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera2/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera3/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera4/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera5/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera6/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera7/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera8/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera9/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
/sensing/camera/camera10/camera_info:
  reliability: reliable
  history: keep_last
  depth: 10
  durability: volatile
