remap:
  - /perception/obstacle_segmentation/pointcloud
  - /perception/object_recognition/objects
  - /perception/object_recognition/tracking/objects
  - /perception/object_recognition/detection/objects
  - /sensing/radar/detected_objects
