topics:
  detection:
    - /perception/object_recognition/detection/centerpoint/objects
    - /perception/object_recognition/detection/centerpoint/validation/objects
    - /perception/object_recognition/detection/clustering/objects
    - /perception/object_recognition/detection/detection_by_tracker/objects
    - /perception/object_recognition/detection/objects_before_filter
    - /perception/object_recognition/detection/objects
  tracking:
    - /perception/object_recognition/tracking/objects
