/tf_static:
  reliability: reliable
  history: keep_last
  depth: 1
  durability: transient_local
/planning/mission_planning/route:
  reliability: reliable
  history: keep_last
  depth: 1
  durability: transient_local
/perception/obstacle_segmentation/pointcloud:
  depth: 10
  durability: volatile
  history: keep_last
  reliability: best_effort
